package org.vaadin.securityauction.shared;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.vaadin.annotations.AutoGenerated;

@SuppressWarnings("serial")
@Entity
@Table(name = "user")
public class User implements Serializable {

    @Id
    @AutoGenerated
    @Column(name = "id")
    private Integer id;

    @Column(name = "username")
    private String username;

    public User() {
        // GWT RPC constructor
    }

    public Integer getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

}
